/*
 * ACTIVE_WINDOW.h
 *
 *  Created on: Aug 11, 2017
 *      Author: nitzan
 */

#ifndef ACTIVE_WINDOW_H_
#define ACTIVE_WINDOW_H_
typedef enum{
	SP_MAIN_WINDOW_ACTIVE,
	SP_LOAD_WINDOW_ACTIVE,
	SP_GAME_WINDOW_ACTIVE,
	SP_MODE_WINDOW_ACTIVE,
	SP_DIFFICULTY_WINDOW_ACTIVE,
	SP_COLOR_WINDOW_ACTIVE,
	SP_EXIT
}ACTIVE_WINDOW;


ACTIVE_WINDOW activeWin;
ACTIVE_WINDOW prevWin;
#endif /* ACTIVE_WINDOW_H_ */
